// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVaoUkeB4UfbFPwa_Nh2fRmfEvZ8ZHV1w',
    appId: '1:324361797194:web:b3aa5159e61e5b338c30b3',
    messagingSenderId: '324361797194',
    projectId: 'bingo-11b68',
    authDomain: 'bingo-11b68.firebaseapp.com',
    storageBucket: 'bingo-11b68.firebasestorage.app',
    measurementId: 'G-H6XVLGVHZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT8iAjRFrvred40fl8Ut4K5jb2y__dp2g',
    appId: '1:324361797194:android:91ad677333a6e3028c30b3',
    messagingSenderId: '324361797194',
    projectId: 'bingo-11b68',
    storageBucket: 'bingo-11b68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT-vD-bjS9zzDi3rtIngsH9FOGRlWQcxE',
    appId: '1:324361797194:ios:728ce5e8ffebdce78c30b3',
    messagingSenderId: '324361797194',
    projectId: 'bingo-11b68',
    storageBucket: 'bingo-11b68.firebasestorage.app',
    iosBundleId: 'com.codepluscircle.bingo',
  );
}
